### ISSUE TITLE
Can't Join Reservation

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#114]
**Current behavior**
Encountered 500 Unique Violation Error when trying to join a reservation.
![image](https://github.com/Joinee-IM/frontend/assets/86758408/388a3475-d8fd-4c3d-a9ff-d3532e535c7f)

**Expected behavior**
Successfully join the reservation and redirect to reservation detail.

**Comment by wsa-2002** [comment]
已經加進去了，重複加會噴這個 error
