### ISSUE TITLE
Change Platform Name to Jöinee for Google Calendar Events

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#118]
**Description**
Use ö for Jöinee.
Also, please have a comprehensive check on your codebase to make sure that our name is displayed as Jöinee, rather than Joinee, in all cases. (probably use search function in vs code to search for Joinee and change it to Jöinee)

If possible, you may change the name of the event to Chinese version.
The title can be [Jöinee 預約] 運動.

**Current behavior**
![image](https://github.com/Joinee-IM/frontend/assets/86758408/83e7b5d5-1712-43e3-9cd1-cc81b086ab65)

**Comment by wsa-2002** [comment]
Hi @corneliaaaaaaa 
fixed in https://github.com/Joinee-IM/backend/commit/c5d6df2bb0d59eeeab48912b167f3bc2146a1443
