### ISSUE TITLE
Wrong reservation info displayed while creating reservation

### ISSUE THREAD

**Issue by wsa-2002** [Joinee-IM/frontend#161]
**Description**
After choosing court 2 and try to create a reservation, create reservation page show that court id is 1.

**Current behavior**

https://github.com/Joinee-IM/frontend/assets/91510760/0fcab63d-2744-4738-862a-ed9f4af07e6a

**Expected behavior**
Should show court 2 instead of 1

**Comment by Lichi0404** [comment]
我覺得這個是 priority 耶
