### ISSUE TITLE
Can't leave reservation

### ISSUE THREAD

**Issue by yyl14** [Joinee-IM/frontend#167]
**Description**
Can't leave reservation. 500 TypeError.

**Current behavior**
Can't leave reservation. 500 TypeError.
<img width="1467" alt="Screenshot 2023-12-20 at 7 46 31 PM" src="https://github.com/Joinee-IM/frontend/assets/81468276/fed04614-6629-4e6b-8f90-0a132170011c">

**Expected behavior**

**Comment by wsa-2002** [comment]
duplicate #171 拍謝先看上面的所以沒看到這個，後端這邊修好了不過有下一個問題，可以去看 reference issue 的 comment 
cc @yyl14
