### ISSUE TITLE
404 error, owner can't leave reservation

### ISSUE THREAD

**Issue by Lichi0404** [Joinee-IM/frontend#171]
**Description**
主揪退出預約顯示 404
**Current behavior**
<img width="1440" alt="image" src="https://github.com/Joinee-IM/frontend/assets/113001576/948526e3-cfb1-4219-b3c9-79abcc022e5b">

**Expected behavior**
應該直接是解散預約，或者要成功退出

**Comment by wsa-2002** [comment]
backend issue, fixing

**Comment by wsa-2002** [comment]
backend api fixed，不過退出之後前端不會轉到其他地方 cc @Donkey0322
