### ISSUE TITLE
button no reactions

### ISSUE THREAD

**Issue by Lichi0404** [Joinee-IM/frontend#183]
**Description**
點選上架場館沒反應
**Current behavior**
<img width="750" alt="image" src="https://github.com/Joinee-IM/frontend/assets/113001576/c917dc5d-153d-4992-b7b4-515b5856cb8d">

**Expected behavior**
應該導去那個頁面

**Comment by yclai1231** [comment]
@corneliaaaaaaa 這邊分兩個點：如果是上架場館，那我們最後就會出現你傳的這張圖的對話筐，讓他選要單純上架場館還是要新增這個場館底下的場地，然後場館相片就是場館相片～
那如果是上架場地的畫面，我們現在把對話筐拿掉了，他就單純只能按上架場地上架一個場地，要多新增別的他就從 header 再來一次，相片的地方會顯示場地相片～
