### ISSUE TITLE
venues and units have different status

### ISSUE THREAD

**Issue by Lichi0404** [Joinee-IM/frontend#184]
**Description**
我下載羽球場地後，羽球網沒被下架
**Current behavior**
<img width="1058" alt="image" src="https://github.com/Joinee-IM/frontend/assets/113001576/fffbfcab-eceb-469c-a7cb-9b897b4bbbdc">

<img width="1027" alt="image" src="https://github.com/Joinee-IM/frontend/assets/113001576/6a10f429-021d-4058-b423-4bb39b7af4a2">

**Expected behavior**
也應顯示下架

**Comment by yclai1231** [comment]
@wsa-2002 Thank u

**Comment by wsa-2002** [comment]
fixed in https://github.com/Joinee-IM/backend/commit/c631a1efa58257ae44b42b3f4d8cfa0b13bfd4c8

**Comment by wsa-2002** [comment]
@yclai1231 @Lichi0404 如果驗證沒問題再幫我關掉
