### ISSUE TITLE
update main page after removing venues

### ISSUE THREAD

**Issue by Lichi0404** [Joinee-IM/frontend#187]
**Description**
我把桌球下架後，我的主頁桌球的 tag 還在
**Current behavior**
<img width="1075" alt="image" src="https://github.com/Joinee-IM/frontend/assets/113001576/1ccdf11c-0d5d-43c6-91de-74fe85bafb31">
<img width="1110" alt="image" src="https://github.com/Joinee-IM/frontend/assets/113001576/c3b8e3f4-348f-4507-97ca-b7bec3ffff13">

**Expected behavior**
tag should be removed

**Comment by wsa-2002** [comment]
fixed in https://github.com/Joinee-IM/backend/commit/aba80d702498fe620ce0b958e91ebe300de3e2dd

**Comment by wsa-2002** [comment]
@Lichi0404 @yclai1231 如果驗證沒問題再幫我關掉
