### ISSUE TITLE
Find Image with Higher Resolution for Mainpage

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#36]
**Description**
The current image on mainpage has low resolution. You may assign the task to UIUX if you want us to find more image with higher resolution to replace current ones.

**Current UI**
<img width="1431" alt="截圖 2023-11-28 12 48 39" src="https://github.com/Joinee-IM/frontend/assets/86758408/6d4a9cff-88c5-499a-a33d-85c6df935928">

**Expected UI**
Just find some image with higher resolution.

**Comment by Donkey0322** [comment]
I replace with some images in another pr(maybe this #26 ), but aiming at better appearance not resolution. In terms of resolution I think I may implement lazy blur loading or some  alternative else.
