### ISSUE TITLE
Adjust Layout of Role Selection Page

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#38]
**Description**
The components on the role selection page are not aligned.

**Current UI**
As you can see, 找運動場 seems to be closer to the left border.
Besides, the distance between our logo & name and 找運動場 & 出租場地 is much larger than the distance between login button and 找運動場 & 出租場地.
<img width="596" alt="截圖 2023-11-28 13 00 50" src="https://github.com/Joinee-IM/frontend/assets/86758408/13b2d14b-8d66-41fe-a410-5b3f775f7754">

**Expected UI**
updatted: 2023/12/6 16:15
The expected UI is as follows:
![image](https://github.com/Joinee-IM/frontend/assets/86758408/b6a4fcb1-985f-47e0-aeec-699b19e96878)

You may want to 
- adjust the bottom margin of logo & name to 0
- increase the left margin of 找運動場

Any adjustment is fine unless it can make the layout look balanced. Thanks!

**Comment by Donkey0322** [comment]
_找運動場 seems to be closer to the left border._
This is because the left image is much wider than the right one, and the label is aligned with the image, so maybe @Joinee-IM/uiux can find the same-series, same-theme, same-size images.

**Comment by Donkey0322** [comment]
@corneliaaaaaaa I'll check with you about the padding issue today.
