### ISSUE TITLE
Change the Sender of Verification Email

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#49]
**Description**
The current sender is letsmeeeeet.

**Current behavior**
![image](https://github.com/Joinee-IM/frontend/assets/86758408/927905ce-a21b-40c1-ae22-55468d335fdd)

**Expected behavior**
The sender should be joinee.

**Comment by Donkey0322** [comment]
@wsa-2002

**Comment by Donkey0322** [comment]
@corneliaaaaaaa Can this issue be closed?
