### ISSUE TITLE
Unable to Create Normal Account

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#59]
**Description**
When I tried to create a normal account (not via google login), I ended up receiving error and could not create one.

**Current behavior**
After I clicked on next step, a snackbar with an error icon, empty string showed up.
![image](https://github.com/Joinee-IM/frontend/assets/86758408/dc476058-73b1-4efd-9351-203c2c8ac36d)

The console message regarding this error:
![image](https://github.com/Joinee-IM/frontend/assets/86758408/f6a7151b-dfbb-473f-9954-447f2b907769)

**Comment by Donkey0322** [comment]
@wsa-2002 I test it on local and it work normally.

**Comment by wsa-2002** [comment]
It seems that this account was already registered at that time, however, dev database had reset, this problem can't be reproduced now.

@corneliaaaaaaa can you help check whether this issue happens again?
@Donkey0322 you may need to handle 409 Email Exists error to notify user that the email is already registered.

**Comment by Donkey0322** [comment]
Can you do it again? I just tried on [staging](https://joinee-ee017.web.app/auth/signup/account?role=NORMAL) and it worked normally. Maybe the backend is awaking.

**Comment by Donkey0322** [comment]
It is speculated that this results from the distance of the server of frontend and backend, and smtp is therefore delayed. I tried to use a existing email and it runs much smoother, considering the correlation. cc @corneliaaaaaaa @wsa-2002 

Maybe this can be solved on production.
