### ISSUE TITLE
Can't See Google Map in Find Stadium Page

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#60]
**Description**
Can't see google map in find stadium page. Have waited for more than 2 minutes but it's still displayed white.

**Current behavior**
![image](https://github.com/Joinee-IM/frontend/assets/86758408/b52532ba-1953-4e52-81c7-b05ff1c4ca01)

**Expected behavior**
Display google map.

**Comment by Donkey0322** [comment]
@wsa-2002 Can you help me figure out the problem? I think firebase preview may not access the correct environment variable stored in GitHub, or does this happen also in production version on GCP?
