### ISSUE TITLE
Change the Link for Verification

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#73]
**Description**
The current link directs users to localhost. Like http://localhost:3000/auth/signup/success?code=f271ef2b-86eb-4eb5-af65-58867977bf4d

**Current behavior**
![image](https://github.com/Joinee-IM/frontend/assets/86758408/775666e2-99e8-454c-9a34-20a0031127ee)

**Expected behavior**
Need to direct users to our wep app. Maybe https://joinee-ee017.web.app/auth/signup/.....

**Comment by wsa-2002** [comment]
這邊 link 是後端訂的，剛剛調整設定讓他會把連結導到 https://joinee-ee017.web.app 了
cc @Donkey0322 @corneliaaaaaaa
