### ISSUE TITLE
Change the Signal for Data Fetching

### ISSUE THREAD

**Issue by corneliaaaaaaa** [Joinee-IM/frontend#74]
**Description**
Currently, we directly display 'isFetching' when the platform is fetching data.

**Current UI**
![image](https://github.com/Joinee-IM/frontend/assets/86758408/b6e12a8d-ea27-472b-9abb-326c84097116)

**Expected UI**
We can change the string to "**Loading...**".
Or
We can use a loading animation, just like the one we used for buttons, in this case.
![image](https://github.com/Joinee-IM/frontend/assets/86758408/ce7def29-cdd8-4e8a-8102-01d95ba04fa4)

**Comment by yclai1231** [comment]
useLoading
